<?php

namespace ContainerYuKyd1A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zst5_VdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zst5.Vd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zst5.Vd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'params' => '?',
        ]);
    }
}
