<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQKYuiQl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQKYuiQl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQKYuiQl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQKYuiQl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQKYuiQl\App_KernelDevDebugContainer([
    'container.build_hash' => 'QKYuiQl',
    'container.build_id' => 'bb67c3f8',
    'container.build_time' => 1762252453,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQKYuiQl');
