<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_e02' => [[], ['_controller' => 'App\\Controller\\E02Controller::index'], [], [['text', '/e02']], [], [], []],
    'App\Controller\E02Controller::index' => [[], ['_controller' => 'App\\Controller\\E02Controller::index'], [], [['text', '/e02']], [], [], []],
];
